name: discovery_api_client_generator
version: 0.2.1
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
description: Create API Client libraries based on the API's Discovery documentation
environment:
  sdk: '>=0.4.3+1.r20444'
dev_dependencies:
  bot: '>=0.16.0'
dependencies:
  unittest: '>=0.4.2'
  args: '>=0.4.2'
  logging: '>=0.4.2+1'
  pathos: '>=0.4.2'
  meta: '>=0.4.2'
