name: discoveryapis_generator
version: 0.6.0
author: Dart Team <misc@dartlang.org>
description: Create API Client libraries based on the Discovery API Service.
homepage: https://github.com/dart-lang/discoveryapis_generator
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.12.1 <0.13.0'
  http: '>=0.11.1 <0.12.0'
  yaml: '>=2.0.0 <3.0.0'
dev_dependencies:
  hop: '>=0.30.2 <0.32.0'
  unittest: '>=0.10.0 <0.12.0'
