name: discovery_api_client_generator
version: 0.3.0-dev
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevin@thinkpixellab.com>
description: Create API Client libraries based on the APIs Discovery documentation
homepage: https://github.com/dart-gde/discovery_api_dart_client_generator
environment:
  sdk: '>=0.6.5'
dependencies:
  args: '>=0.6.5'
  logging: '>=0.6.5'
  meta: '>=0.6.5'
  path: '>=0.6.5'
dev_dependencies:
  bot_io: '>=0.22.0+1'
  hop: '>=0.24.0'
  unittest: '>=0.6.5'
