name: discovery_api_client_generator
version: 0.4.4
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <github@j832.com>
description: Create API Client libraries based on the APIs Discovery documentation
homepage: https://github.com/dart-gde/discovery_api_dart_client_generator
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.11.0'
  google_discovery_v1_api: '0.4.11-dev.1'
  logging: '>=0.9.1+1 <0.10.0'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  bot_io: '>=0.25.0 <0.26.0'
  hop: '>=0.30.2 <0.31.0'
  unittest: '>=0.10.0 <0.11.0'
