name: discovery_api_client_generator
version: 0.2.8
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevin@thinkpixellab.com>
description: Create API Client libraries based on the APIs Discovery documentation
homepage: https://github.com/dart-gde/discovery_api_dart_client_generator
environment:
  sdk: '>=0.5.13'
dependencies:
  args: '>=0.5.13'
  logging: '>=0.5.13'
  pathos: '>=0.5.13'
dev_dependencies:
  hop: '>=0.22.2'
  unittest: '>=0.5.13'
